### ISSUE TITLE
question

### ISSUE THREAD

**Issue by gregf** [masasam/emacs-helm-tramp#1]
Sorry to spam your issues with this, but what color scheme are you using in your screenshots, I love it.

**Comment by masasam** [comment]
Hi greg!
I am useing material-theme.
See http://melpa.org/#/material-theme
The base is a material theme, but I'm customizing a bit.
See https://github.com/masasam/dotfiles/blob/master/.emacs.d/inits/99_custom.el

**Comment by gregf** [comment]
Thanks!
