### ISSUE TITLE
Request: add from controlmaster paths

### ISSUE THREAD

**Issue by indigoviolet** [masasam/emacs-helm-tramp#12]
I have in `.ssh/config`

```
Host *
  ControlMaster auto
  ControlPath ~/.ssh/master-%r@%h:%p
  ControlPersist 30m
  ForwardAgent yes
  ServerAliveInterval 60
```

This makes files like

```
➜ ls ~/.ssh/master*
/home/venky/.ssh/master-ubuntu@3.87.42.213:22  /home/venky/.ssh/master-venky@192.168.199.142:1741
```

Which would be really nice to have in helm-tramp's completion list.

**Comment by masasam** [comment]
Hi @indigoviolet .
Thank you for comment.
I think it should be done as follows.

```
* TRAMP does not use default ssh ControlPath
TRAMP overwrites ControlPath settings when initiating ssh sessions. TRAMP does this to fend off a stall if a master session opened outside the Emacs session is no longer open. That is why TRAMP prompts for the password again even if there is an ssh already open.

Some ssh versions support a ControlPersist option, which allows you to set the ControlPath provided the variable tramp-ssh-controlmaster-options is customized as follows:

(customize-set-variable
 'tramp-ssh-controlmaster-options
 (concat
   "-o ControlPath=/tmp/ssh-ControlPath-%%r@%%h:%%p "
   "-o ControlMaster=auto -o ControlPersist=yes"))
Note how "%r", "%h" and "%p" must be encoded as "%%r", "%%h" and "%%p".

If the ~/.ssh/config is configured appropriately for the above behavior, then any changes to ssh can be suppressed with this nil setting:

(customize-set-variable 'tramp-use-ssh-controlmaster-options nil)
```
See https://www.gnu.org/software/tramp/ .

**Comment by indigoviolet** [comment]
Thanks for the quick response @masasam . I suspect we're talking about slightly different things here - though. I already have `(customize-set-variable 'tramp-use-ssh-controlmaster-options nil)`, which as I understand it causes Tramp to use settings from `.ssh/config`. 

However, my goal is different: I want for `helm-tramp` to use the existing ControlPath files as a way of populating the tramp completion list in emacs (similar to how it populates hosts from .ssh/config). This way, if I have ssh-ed into some server, I can also use Tramp in my emacs to open files on that server easily.

**Comment by masasam** [comment]
Hi @indigoviolet .
I've supported ssh controlmaster path at https://github.com/masasam/emacs-helm-tramp/commit/6790bd2f6e092b2a4131103fa672fa3ba9f0c2bf .
You can use it as follows.
```
(setq helm-tramp-control-master t)
```

**Comment by indigoviolet** [comment]
wow, that was super quick! I will test it out tonight and let you know. Thank you!
