### ISSUE TITLE
Support for SFTP

### ISSUE THREAD

**Issue by mapolone** [masasam/emacs-helm-tramp#13]
Hello,
is there a reason why `sftp` is not supported as transfer method?
In tramp mode (with or without helm) I'm able to connect via SFTP where needed. I'm running Emacs 26.2 built from sources.

**Comment by masasam** [comment]
Hi @mapolone .
Thank you for comment.
You can connect with sftp if you set the following.

    (setq tramp-default-method "sftp")

**Comment by mapolone** [comment]
That's great thank you so much!
