### ISSUE TITLE
Remove risky config from examples

### ISSUE THREAD

**Issue by pstn** [masasam/emacs-helm-tramp#14]
The example for ssh contains the line [ForwardAgent yes](https://github.com/masasam/emacs-helm-tramp/blame/master/README.md#L164), which the openssh documentation calls  risky because it leads to attack vectors from the server to the client. Since it is not necessary for helm-tramp to work and user blindly copy examples I think it should be removed.

**Comment by masasam** [comment]
@pstn That's right, so I deleted it at https://github.com/masasam/emacs-helm-tramp/commit/55e56975fe1456591a293bf60c183c3dda9f788f .
Thank you for teaching me.
