### ISSUE TITLE
Problem with multiple host values in .ssh/config

### ISSUE THREAD

**Issue by Kinmarui** [masasam/emacs-helm-tramp#8]
Hi, great plugin I started it using today, but I encountered problem when I have defined in .ssh/config configuration using multiple host values i.e.

```
Host cat dog spider 
  HostName %h.domain.com
  * skipped rest of config *
```
it normaly resolves to 3 domains with the same configuration
- cat.domain.com
- dog.domain.com
- spider.domain.com

but your plugin doesn't support it :< is there a easy fix for that? Host line should be splitted by space character into array.

definitions from man can be found nicely clipped on [SE](https://unix.stackexchange.com/a/61666)

Edit: I believe fragment from line [81](https://github.com/masasam/emacs-helm-tramp/blob/master/helm-tramp.el#L81) should be modified to use regex returning list but I have never writen lisp code (it's amazingly readable)

**Comment by masasam** [comment]
Hi @Kinmarui .
I didn't know this specification of ssh_config.
I've fixed it now.
Changes will be reflected in melpa after 6 hours.
Thank you for your imformation.

**Comment by Kinmarui** [comment]
Hi @masasam 
thanks for quick fix ❤️ , everything works. 
This specification of ssh is really usefull when you have the same user on multiple machines in the same domain.
